project:
  type: website
  output-dir: docs

website:
  title: "Ani Shaikova"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/AniShaikova
      - icon: envelope
        href: mailto:aniuser@bu.edu
  page-footer:
    center: "© 2026 Ani Shaikova · Built with Quarto"

format:
  html:
    theme: litera
    css: styles.css
    toc: false
